### ISSUE TITLE
Add support for app_id parameter.

### ISSUE THREAD

**Issue by jkbpvsc** [Rob--/bitskins#1]
Bitskins now support multiple game inventories.
You can specify which you games inv you want to use with `app_id` param in your request body.
Leaving it empty defaults to CS:GO

**Comment by qlerebours** [comment]
I would need it too but i'll see if I have to time to make a PR

**Comment by ghost** [comment]
I have the same exact problem. I need pubg data not csgo

**Comment by Rob--** [comment]
Sorry my dudes I will update this soon. Without reading the Bitskins docs, is the only thing that requires a change adding "app_id" param to queries?

**Comment by jkbpvsc** [comment]
It was last year, Ill double check on it now

EDIT
Still the same. You just add the `app_id` param to the queries

**Comment by jkbpvsc** [comment]
\>>[https://github.com/Rob--/bitskins/pull/2](https://github.com/Rob--/bitskins/pull/2)
