### ISSUE TITLE
Promise { <pending> }

### ISSUE THREAD

**Issue by quo91** [Rob--/bitskins#6]
No matter what function I use I always get "Promise { <pending> }" as a response. Any ideas why?

**Comment by pujitm** [comment]
I don't think this is an issue; Promises are extremely useful when dealing with web clients

**Comment by pujitm** [comment]
@Rob-- can we close this issue?

**Comment by Rob--** [comment]
@DarthWindu agreed.

@quo91 Either use `async` and `await`:

```javascript
async function main() {
  const response = await api.getAccountBalance();
}
```

Or just use promises normally:

```javascript
api.getAccountBalance().then(console.log);
```
